console.log(document.getElementsByTagName("title")[0].textContent.toLocaleUpperCase());
var inputNombre = document.getElementById("nombre");
var inputApellido = document.getElementById("apellido");
inputNombre.name = "Manuel";
inputApellido.name = "Verdejo";
var parrafo = document.getElementById("saludo");
parrafo.textContent = "Hola " + inputNombre.name + " " + inputApellido.name;
var nuevoParrafo = document.createElement("p");
nuevoParrafo.textContent = "¿Qué tal estás?";
parrafo.insertAdjacentElement("afterend", nuevoParrafo);
var label = document.querySelector('label[for="apellido"]');
label.textContent = "Apellidos:";